apiVersion: flagger.app/v1alpha3
kind: Canary
metadata:
  name: sinfo
  namespace: canaryns
spec:
  # deployment reference
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sinfo
  # the maximum time in seconds for the canary deployment
  # to make progress before it is rollback (default 600s)
  progressDeadlineSeconds: 60
  # HPA reference (optional)
  autoscalerRef:
    apiVersion: autoscaling/v2beta1
    kind: HorizontalPodAutoscaler
    name: sinfo
  service:
    # container port
    port: 8080
    # Istio gateways (optional)
    gateways:
#      - public-gateway.istio-system.svc.cluster.local
      - bookinfo-gateway.default
    # Istio virtual service host names (optional)
    hosts:
      - "app.shawn.com"
  skipAnalysis: false
  canaryAnalysis:
    # schedule interval (default 60s)
    interval: 1m
    # max number of failed metric checks before rollback
    threshold: 5
    # max traffic percentage routed to canary
    # percentage (0-100)
    maxWeight: 50
    # canary increment step
    # percentage (0-100)
    stepWeight: 10
    metrics:
      - name: request-success-rate
        # minimum req success rate (non 5xx responses)
        # percentage (0-100)
        threshold: 99
        interval: 1m
      - name: request-duration
        # maximum req duration P99
        # milliseconds
        threshold: 500
        interval: 30s
    # generate traffic during analysis
    webhooks:
      - name: load-test
        url: http://flagger-loadtester.canaryns/
        timeout: 5s
        metadata:
          cmd: "hey -z 1m -q 10 -c 2 http://sinfo-canary.canaryns:8080/"